### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by retrodjradio** [jailsonsb2/Radioplayer_api#4]
Zdravím,

po 7 dnech perfektního fungování z ničeho nic nejdou Metadata, na index.html se nezobrazí název skladby ani internet, soubory nowplaying.txt a artwork.jpg fungují správně, opravdu už si nevím rady, děkuji moc za pomoc, retro dj radio na webu https://retrodjradio.cz

Hello,

after 7 days of perfect functioning, Metadata is gone, index.html does not show track name or internet, files nowplaying.txt and artwork.jpg work correctly, I really don't know anymore, thank you very much for your help, retro dj radio on the website https  ://retrodjradio.cz

**Comment by jailsonsb2** [comment]
![image](https://github.com/user-attachments/assets/9b0ca20c-7c81-4ef7-b0f7-4bccc935a685)

The Streamafrica API has been down since yesterday, but that's okay. You can easily switch to my API by simply entering the main.js file that is located on your server at https://retrodjradio.cz/js/main.js. You will need to edit this file and where the line is as shown in the image, it should look like this:

const API_KEY_LYRICS = "1637b78dc3b129e6843ed674489a92d0";
const API_URL = "https://twj.es/radio_info/?radio_url=";
//const API_URL = "https://api-v2.streamafrica.net/icyv2?url=";
const TIME_TO_REFRESH = window?.streams?.timeRefresh || 10000;

**Comment by jailsonsb2** [comment]
Alternatively, you can simply edit the section in your index as shown in the image below,

![image](https://github.com/user-attachments/assets/0555df53-04c9-41f4-9f86-e1e0decb79b2)

https://twj.es/radio_info/?radio_url=https://icecast1.play.cz/retrodjradio.mp3

![image](https://github.com/user-attachments/assets/0b5c7291-bcdf-4b87-b4e3-445d2f1cac77)

Choose one of the 2 alternatives
